cluster: export TMPDIR=/data/extended/$USER; mkdir -p $TMPDIR;
  module load slurm && mkdir -p {resources.logdir}/cluster/`date +"%F"`/{rule} &&
  sbatch --partition={resources.partition} --ntasks-per-node 1 --cpus-per-task={threads}
  --mem={resources.mem_mb} --job-name=smk-{rule}-{wildcards} --output={resources.logdir}/cluster/`date
  +"%F"`/{rule}/{rule}-{wildcards}-`date +"%H%m%S"`-job%j.out --error={resources.logdir}/cluster/`date
  +"%F"`/{rule}/{rule}-{wildcards}-`date +"%H%m%S"`-job%j.err --parsable --export=TMPDIR
cluster-cancel: cluster-cancel.sh
cluster-cancel-nargs: 50
cluster-status: status-scontrol.sh
conda-prefix: /package/mamba/envs/pore-c-mpi_envs
default-resources:
- partition=bioinfo
- mem_mb=2400
- disk_mb=2400
- logdir=logs
jobscript: slurm-jobscript.sh
keep-going: true
latency-wait: 300
local-cores: 2
max-jobs-per-second: 1
max-status-checks-per-second: 1
printshellcmds: true
rerun-incomplete: true
restart-times: 1
scheduler: greedy
use-conda: true
use-singularity: false
